name: Michal Randak
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
defaults:
  -
    scope:
      path: ""
    values:
      nickname: "Gobanit"
      main_title: "Gobanit Web"
      title: "Gobanit Static Web"

