name: Michal Randak
markdown: kramdown
# BibTex Citation plugin
citation:
    citation_style: apa
    citation_locale: en
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
defaults:
  -
    scope:
      path: ""
    values:
      nickname: "Gobanit"
      main_title: "Gobanit Web"
      title: "Gobanit Static Web"
collections:
    game_projects:


